In [2]:
import numpy as np

X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [3]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
# (The 1st being index 0)

Z = X[1:4, 2:5]
# We print Z
print('Z = \n', Z)



[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [4]:
W = X[1:, 2:5]
print()
print('W = \n', W)



W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
