In [1]:
import numpy as np

X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [2]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
# (The 1st being index 0)

Z = X[1:4, 2:5]
# We print Z
print('Z = \n', Z)



Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [3]:
W = X[1:, 2:5]
print()
print('W = \n', W)



W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [4]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns

Y = X[:3, 2:5]
print()
print('Y = \n', Y)


Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [5]:
# we select all the elements in the 3rd row
q = X[2,:]
print()
print('q = \n', q)


q = 
 [10 11 12 13 14]


In [6]:
# we select all the elements in the 3rd column
q = X[:,2]
print()
print('q = \n', q)


q = 
 [ 2  7 12 17]


In [7]:
R = X[:, 2:3]

# We print R
print()
print('R = \n', R)


R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [8]:
X = np.arange(20).reshape(4, 5)
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [9]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



In [10]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [11]:
Z = np.copy(X[1:4, 2:5])
W = X[1:4, 2:5].copy()
Z[2, 2] = 555
W[2, 2] = 444
# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


In [14]:
import numpy as np

X = np.random.randint(1,20,size=(50,5))
print("Shape of X is: ", X.shape)

Shape of X is:  (50, 5)


In [15]:
row_indices = np.random.randint(1,50,size=10)
print("Random 10 indices are: ", row_indices)

Random 10 indices are:  [ 5 35 33 33 20 31 24  7 34 26]


In [16]:
X_subset = X[row_indices, :]
print(X_subset)

# To Do 2 - Print those rows of X whose indices are present in row_indices[4:8]
X_subset = X[row_indices[4:8], :]
print(X_subset)

[[18  6  7  9 18]
 [10 17  4 11 16]
 [10 13  7 18 19]
 [10 13  7 18 19]
 [ 2  5 15  1  1]
 [ 3 12  9  3 17]
 [ 6 19  3  4 12]
 [ 4 12 13 16  7]
 [ 2  6  3  8 12]
 [14 11 18  5 13]]
[[ 2  5 15  1  1]
 [ 3 12  9  3 17]
 [ 6 19  3  4 12]
 [ 4 12 13 16  7]]


In [17]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()



X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]



In [18]:
print('z = ', np.diag(X))
print('y = ', np.diag(X, k=1))
print('w = ', np.diag(X, k=-1))

z =  [ 0  6 12 18 24]
y =  [ 1  7 13 19]
w =  [ 5 11 17 23]


In [19]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]
