In [2]:
import numpy as np

X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [3]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
# (The 1st being index 0)

Z = X[1:4, 2:5]
# We print Z
print('Z = \n', Z)



[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [4]:
W = X[1:, 2:5]
print()
print('W = \n', W)



W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [5]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns

Y = X[:3, 2:5]
print()
print('Y = \n', Y)


Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [8]:
# we select all the elements in the 3rd row
q = X[2,:]
print()
print('q = \n', q)


q = 
 [10 11 12 13 14]


In [9]:
# we select all the elements in the 3rd column
q = X[:,2]
print()
print('q = \n', q)


q = 
 [ 2  7 12 17]


In [10]:
R = X[:, 2:3]

# We print R
print()
print('R = \n', R)


R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [11]:
X = np.arange(20).reshape(4, 5)
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [12]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



In [14]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [15]:
Z = np.copy(X[1:4, 2:5])
W = X[1:4, 2:5].copy()
Z[2, 2] = 555
W[2, 2] = 444
# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]
