In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])


x =  [1 2 3 4 5]

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


In [3]:
x[3] = 20

print("Modified: \n x = ", x)

Modified: 
 x =  [ 1  2  3 20  5]


In [5]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print()
print("X = \n", X)
print()

print("This is (0, 0) Element in X: ", X[0, 0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0, 0) Element in X:  1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [6]:
# We print the original x
print()
print('Original:\n X = \n', X)
print()

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [8]:
x = np.array([1, 2, 3, 4, 5])

Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print()
print("Original x = ", x)

x = np.delete(x, [0, 4])

print()
print("Modified x = ", x)

print()
print("Original Y = ", Y)

w = np.delete(Y, 0, axis=0)

v = np.delete(Y, [0, 2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


In [10]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

x = np.append(x, 6)

# We print x
print()
print('x = ', x)

x = np.append(x, [7, 8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

v = np.append(Y, [[7, 8, 9]], axis=0)
q = np.append(Y, [[9], [10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]
