In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)

[1 2 3 4 5 6]


In [3]:
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(6,)

In [7]:
x = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
x.shape

(4, 3)

In [9]:
x.size

12

In [11]:
x = np.array(["Hello", "World"])

In [13]:
print("Type: ", type(x))
print("D type: ", x.dtype)
print("Shape: ", x.shape)

Type:  <class 'numpy.ndarray'>
D type:  <U5
Shape:  (2,)


In [16]:
x = np.array([1, 2, "Hello world"])
print("Shape: ", x.shape)
print("Type: ", type(x))
print("DType: ", x.dtype)

Shape:  (3,)
Type:  <class 'numpy.ndarray'>
DType:  <U21


In [17]:
x = np.array([1.4, 4.5, 5.9], dtype=np.int64)
print(x)

[1 4 5]


In [18]:
np.save("my_array", x)

In [20]:
print(np.load("my_array.npy"))
print(x.ndim)

[1 4 5]
1
