In [2]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
print(x.dtype)

int64


In [7]:
x = np.ones((4, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
x = np.full((4, 5), 5)
print(x)
print("D-Type: ", x.dtype)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
D-Type:  int64


In [11]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
x = np.zeros((3, 4))
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has diamensions:  (3, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [14]:
x = np.ones((3, 4))
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
X has diamensions:  (3, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [20]:
x = np.full((2, 4), 6)
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[6 6 6 6]
 [6 6 6 6]]
X has diamensions:  (2, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  int64


In [23]:
x = np.eye(5)
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has diamensions:  (5, 5)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [24]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

