In [2]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
print(x.dtype)

int64


In [7]:
x = np.ones((4, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
x = np.full((4, 5), 5)
print(x)
print("D-Type: ", x.dtype)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
D-Type:  int64


In [11]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
x = np.zeros((3, 4))
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has diamensions:  (3, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [14]:
x = np.ones((3, 4))
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
X has diamensions:  (3, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [20]:
x = np.full((2, 4), 6)
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[6 6 6 6]
 [6 6 6 6]]
X has diamensions:  (2, 4)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  int64


In [23]:
x = np.eye(5)
print("X = \n", x)
print("X has diamensions: ", x.shape)
print("X is an object of type: ", type(x))
print("The elements in X are of type: ", x.dtype)

X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has diamensions:  (5, 5)
X is an object of type:  <class 'numpy.ndarray'>
The elements in X are of type:  float64


In [24]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



In [26]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 



x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [28]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1, 14, 3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [31]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
x = np.linspace(0, 25, 10)
print("x = \n", x)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [32]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
x = np.linspace(0, 25, 10, endpoint=False)
print("x = \n", x)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [38]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

x = np.reshape(x, (2, 10))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

x has dimensions: (2, 10)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [39]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [40]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [45]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3, 3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.2214013  0.93419454 0.81547494]
 [0.06118199 0.71373661 0.25346839]
 [0.74524693 0.57374915 0.96905549]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [48]:
X = np.random.randint(4, 15, size = (3, 2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 6 12]
 [10  7]
 [ 5  6]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [49]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.

X = np.random.normal(0, 0.1, size=(1000, 1000))

# We print X
print()
print('X = \n', X)
print()
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.01949659  0.0123151   0.10333852 ...  0.06653563 -0.13380434
   0.10976994]
 [ 0.01152969 -0.01752636  0.08460701 ... -0.25242506  0.06220674
   0.01047875]
 [-0.13236659  0.07992489  0.12682569 ... -0.10798092 -0.01081003
   0.03927353]
 ...
 [ 0.02840355  0.01290175 -0.06904448 ... -0.09898634  0.01176229
   0.04203085]
 [ 0.17859361 -0.09164106  0.02795096 ... -0.01526324  0.04120502
   0.02900845]
 [-0.10730939  0.01493036  0.14948839 ...  0.02881663 -0.02867318
  -0.04547985]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -7.82888540042728e-05
The maximum value in X is: 0.48705948219184514
The minimum value in X is: -0.46347253362589297
X has 500515 negative numbers
X has 499485 positive numbers
